config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
   get 'home/precios'
  post '/home/precios' => 'home/precios'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    require 'net/http'
    require 'json'
    # Para obtener las noticias
    @url = 'https://min-api.cryptocompare.com/data/v2/news/?lang=ES'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @news = JSON.parse(@response)

     # Para obtener los precios
    @precios_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,FTH,XRP,BCH,FOS,LTC,ADA,XLM,MIOTA,USDT,TRX&tsyms=EUR'
    @precios_uri = URI(@precios_url)
    @precios_response = Net::HTTP.get(@precios_uri)
    @precios = JSON.parse(@precios_response)
    
  end

  def precios

    require 'net/http'
    require 'json'

    @simbolo = params[:sym]
    if @simbolo
      @simbolo = @simbolo.upcase
      
      # Para obtener los precios
      @cuota_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms='+@simbolo+'&tsyms=EUR'
      @cuota_uri = URI(@cuota_url)
      @cuota_response = Net::HTTP.get(@cuota_uri)
      @cuota = JSON.parse(@cuota_response)
    end

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
  <div class="container-fluid">
    
    <%= link_to "CriptoNoticias", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          
          <%= link_to "Precios", home_precios_path, class: "nav-link" %>
        </li>
       
        
      </ul>

      <%= form_tag home_precios_path, :method => 'POST', class: "d-flex" do %>
      <%= text_field_tag 'sym', nil, placeholder: "Buscar criptomonedas", class: "form-control me-2" %>
      <%= submit_tag 'Buscar', class:"btn btn-outline-light" %>
      <% end %>

     </div> 
  </div>
</nav>

app/views/home/index.html.erb
<% @precios["DISPLAY"] %>



<table class="table table-responsive table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th scope="col">SÍMBOLO</th>
      <th scope="col">PRECIO</th>
      <th scope="col">V+ALTO(24H)</th>
      <th scope="col">V+BAJO(24H)</th>
      <th scope="col">MarketCap</th>
    </tr>
  </thead>
  <tbody>
  	<% @precios["DISPLAY"].each do |clave, valor| %>
    <tr>
      <th scope="row"><%= clave %></th>
      <td><%= valor["EUR"]["PRICE"] %></td>
      <td><%= valor["EUR"]["HIGHDAY"] %></td>
      <td><%= valor["EUR"]["LOWDAY"] %></td>
      <td><%= valor["EUR"]["MKTCAP"] %></td>
    </tr>
    <% end %>
  </tbody>
</table>



<br/><br/>
<div class="container">
	<div class="row">
		<% for x in @news["Data"] %>
		  	<div class="col-sm" >
			  	<div class="card" style="width: 18rem;">
				  <img src="<%= x["imageurl"] %>" class="card-img-top" alt="<%= x["source"] %>">
				  <div class="card-body">
				    <h5 class="card-title"><%= x["title"] %></h5>
				    <p class="card-text"><%= x["body"] %></p>
				    <a href="<%= x["url"] %>" class="btn btn-primary">Leer mas ...</a>
				  </div>
				</div>
				<br/>
			</div>

		<% end %>
	</div>
</div>

app/views/home/precios.html.erb
<h1>Página de precios</h1>


<% if @simbolo %>
	<% if @cuota['Response'] %>
		<p> Por favor, escriba un símbolo de criptomoneda válido</p>
	<% else %>
		<table class="table table-responsive table-striped table-hover table-bordered">
		  <thead class="table-dark">
		    <tr>
		      <th scope="col">SÍMBOLO</th>
		      <th scope="col">PRECIO</th>
		      <th scope="col">V+ALTO(24H)</th>
		      <th scope="col">V+BAJO(24H)</th>
		      <th scope="col">MarketCap</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<% @cuota["DISPLAY"].each do |clave, valor| %>
		    <tr>
		      <th scope="row"><%= clave %></th>
		      <td><%= valor["EUR"]["PRICE"] %></td>
		      <td><%= valor["EUR"]["HIGHDAY"] %></td>
		      <td><%= valor["EUR"]["LOWDAY"] %></td>
		      <td><%= valor["EUR"]["MKTCAP"] %></td>
		    </tr>
		    <% end %>
		  </tbody>
		</table>
	<% end %>	
<% else %>
	<p> Por favor, escriba el símbolo de la criptomoneda a buscar</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Criptonoticias</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <br/>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>